version: '3.8'
services:

  postgres:
    image: postgres
    environment:
        POSTGRES_DB: gdz_main
        POSTGRES_USER: root
        POSTGRES_PASSWORD: rootpass
    ports:
      - "5432:5432"
    volumes:
    - ./volumes/db:/var/lib/postgresql/data

  gdzbot:
    build: ./gdzbot
    depends_on:
      - postgres
    command: tail -f /dev/null
    volumes:
    - ./volumes/gdzbot/:/gzdbot

volumes:
  db:
  gdzbot:

