version: '3.8'
services:
  postgres:
    image: postgres
    environment:
        POSTGRES_DB: gdz_main
        POSTGRES_USER: root
        POSTGRES_PASSWORD: rootpass
    ports:
      - "5432:5432"
    volumes:
    - db:/var/lib/postgresql/data
  gdz-bot:
    build: ./docker_gdzbot
    depends_on:
      - postgres

volumes:
  db:
  gdzbot:

